# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd2c098d7188691e332824cbc11254038b4e11e579fb9f6e0df9f959bb07cb106e447567ca222070c1413a815b2c47ab68fb16c0801667b07196cd8a7ad20801

test:
  secret_key_base: 9c066e6a672a10d1f4bace3f5d295f9f973cdd7e44699051460fea039c7d28eed91983b39e04a5fff753d297895daa300a23797750098bbc84aa0117e147f389

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
